version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      chrome:
        condition: service_healthy
    environment:
      DRY_RUN: ${DRY_RUN}
      CHROME_HOST: ${CHROME_HOST}
      DATA_LOCATION: ${DATA_LOCATION}
      MASTODON_TOKEN: ${MASTODON_TOKEN}
      BLUESKY_HANDLE: ${BLUESKY_HANDLE}
      BLUESKY_PASSWORD: ${BLUESKY_PASSWORD}
    volumes:
      - bot_data:/usr/src/app/data
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  chrome:
    image: "browserless/chrome:latest"
    shm_size: 2g
    ports:
      - "8890:3000"
    restart: unless-stopped
    environment:
      - MAX_CONCURRENT_SESSIONS=1
      - MAX_QUEUE_LENGTH=0
      - DEFAULT_BLOCK_ADS=true
      - HOST=0.0.0.0
      - CONNECTION_TIMEOUT=600000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 2s
      timeout: 2s
      retries: 5
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
volumes:
  bot_data:
